/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import Business.EcoSystem;
import Business.PaymentHistory.CustomerTransaction;
import Business.User.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rushang
 */
public class CheckoutPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckoutPanel
     */
    EcoSystem system;
    User user;
    float totalAmount;

    public CheckoutPanel(EcoSystem system, User user) {
        initComponents();
        this.system = system;
        this.user = user;

        totalAmountTxt.setEditable(false);
        totalAmount = 0;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalAmountTxt = new javax.swing.JTextField();
        checkoutBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 102, 255));
        setLayout(null);

        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Facility Used", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(checkoutTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(150, 100, 1210, 450);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Checkout Page");
        add(jLabel1);
        jLabel1.setBounds(609, 40, 230, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Total Amount:");
        add(jLabel2);
        jLabel2.setBounds(597, 600, 190, 30);
        add(totalAmountTxt);
        totalAmountTxt.setBounds(810, 600, 320, 40);

        checkoutBtn.setBackground(new java.awt.Color(0, 0, 0));
        checkoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBtn.setText("Checkout");
        checkoutBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });
        add(checkoutBtn);
        checkoutBtn.setBounds(950, 680, 180, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this, "Your total bill is: " + totalAmount);
    }//GEN-LAST:event_checkoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JTable checkoutTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField totalAmountTxt;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) checkoutTable.getModel();
        model.setRowCount(0);
        int index = 1;

        for (CustomerTransaction transaction : system.getCustomerTransactionDirectory().getCustomerTransactionList()) {

            if (transaction.getUserId().equals(user.getUserId())) {
                totalAmount += transaction.getPrice();

                Object[] row = new Object[3];

                row[0] = index;
                row[1] = transaction.getFacilityUsed();
                row[2] = transaction.getPrice();

                model.addRow(row);
                index++;
            }
        }

        totalAmountTxt.setText(String.valueOf(totalAmount));
    }
}
