/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import Business.EcoSystem;
import Business.User.User;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Rushang
 */
public class CustomerHomePanel extends JPanel {

    EcoSystem system;
    User user;
    private Image backgroundImage;
    
  

    /**
     * Creates new form CustomerHome
     */
    public CustomerHomePanel(EcoSystem system, User user) {
        initComponents();
        this.system = system;
        this.user = user;

        // Load the background image
        backgroundImage = new ImageIcon(getClass().getResource("/images/welcome-user.jpg")).getImage();

        // Set the user's name on the label
        jLabel3.setText(user.getFirstName() + " " + user.getLastName());

        // Ensure the background is painted
        userRightPanel.repaint();
    }

    
//    Need to fix this 
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        // Draw background only for the right panel
        if (backgroundImage != null && userRightPanel != null) {
            // Use the userRightPanel's bounds for positioning and sizing the image
            g.drawImage(backgroundImage, 0, 0, userRightPanel.getWidth(), userRightPanel.getHeight(), this);
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        userRightPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userLeftPanel = new javax.swing.JPanel();
        bookVehicleBtn = new javax.swing.JButton();
        bookPoolBtn = new javax.swing.JButton();
        bookGameBtn = new javax.swing.JButton();
        bookLaundryBtn = new javax.swing.JButton();
        shopBtn = new javax.swing.JButton();
        checkOutBtn = new javax.swing.JButton();
        bookFoodBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        userRightPanel.setBackground(new java.awt.Color(204, 102, 255));
        userRightPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel2.setText("Welcome to Your Home Away from Home");
        userRightPanel.add(jLabel2);
        jLabel2.setBounds(100, 60, 770, 43);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userRightPanel.add(jLabel3);
        jLabel3.setBounds(350, 210, 240, 40);

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Crafting Moments, Just the Way You Like Them");
        userRightPanel.add(jLabel4);
        jLabel4.setBounds(200, 130, 590, 30);

        jSplitPane1.setRightComponent(userRightPanel);

        userLeftPanel.setBackground(new java.awt.Color(204, 102, 255));

        bookVehicleBtn.setBackground(new java.awt.Color(0, 0, 0));
        bookVehicleBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookVehicleBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookVehicleBtn.setText("Book Vehicle");
        bookVehicleBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bookVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookVehicleBtnActionPerformed(evt);
            }
        });

        bookPoolBtn.setBackground(new java.awt.Color(0, 0, 0));
        bookPoolBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookPoolBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookPoolBtn.setText("Book Pool");
        bookPoolBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bookPoolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPoolBtnActionPerformed(evt);
            }
        });

        bookGameBtn.setBackground(new java.awt.Color(0, 0, 0));
        bookGameBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookGameBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookGameBtn.setText("Book Games");
        bookGameBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bookGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookGameBtnActionPerformed(evt);
            }
        });

        bookLaundryBtn.setBackground(new java.awt.Color(0, 0, 0));
        bookLaundryBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookLaundryBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookLaundryBtn.setText("Laundry");
        bookLaundryBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bookLaundryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookLaundryBtnActionPerformed(evt);
            }
        });

        shopBtn.setBackground(new java.awt.Color(0, 0, 0));
        shopBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        shopBtn.setForeground(new java.awt.Color(255, 255, 255));
        shopBtn.setText("Souvenir Shop");
        shopBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        shopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopBtnActionPerformed(evt);
            }
        });

        checkOutBtn.setBackground(new java.awt.Color(0, 0, 0));
        checkOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkOutBtn.setText("Checkout");
        checkOutBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        bookFoodBtn.setBackground(new java.awt.Color(0, 0, 0));
        bookFoodBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookFoodBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookFoodBtn.setText("Food and Beverage");
        bookFoodBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bookFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFoodBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userLeftPanelLayout = new javax.swing.GroupLayout(userLeftPanel);
        userLeftPanel.setLayout(userLeftPanelLayout);
        userLeftPanelLayout.setHorizontalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bookVehicleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookPoolBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bookFoodBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bookLaundryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shopBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(checkOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        userLeftPanelLayout.setVerticalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(bookVehicleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(bookPoolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(bookGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(bookFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(bookLaundryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(shopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );

        jSplitPane1.setLeftComponent(userLeftPanel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void shopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopBtnActionPerformed
        // Redirect User to Shopping Panel
        ShopPanel bookShop = new ShopPanel(system, user);
        jSplitPane1.setRightComponent(bookShop);
    }//GEN-LAST:event_shopBtnActionPerformed

    private void bookVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookVehicleBtnActionPerformed
        // Redirect User to Vehicle Booking Panel
        VehicleBookingPanel bookVehicle = new VehicleBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookVehicle);
    }//GEN-LAST:event_bookVehicleBtnActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        // TODO add your handling code here:
        CheckoutPanel checkout = new CheckoutPanel(system, user);
        jSplitPane1.setRightComponent(checkout);
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void bookFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFoodBtnActionPerformed
        // TODO add your handling code here:
        FoodBookingPanel bookFood = new FoodBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookFood);
    }//GEN-LAST:event_bookFoodBtnActionPerformed

    private void bookPoolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPoolBtnActionPerformed
        // TODO add your handling code here:
        PoolBookingPanel bookPool = new PoolBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookPool);
    }//GEN-LAST:event_bookPoolBtnActionPerformed

    private void bookGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookGameBtnActionPerformed
        // TODO add your handling code here:
        GameBookingPanel bookGame = new GameBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookGame);
    }//GEN-LAST:event_bookGameBtnActionPerformed

    private void bookLaundryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookLaundryBtnActionPerformed
        // TODO add your handling code here:
        LaundryPanel bookLaundry = new LaundryPanel(system, user);
        jSplitPane1.setRightComponent(bookLaundry);
    }//GEN-LAST:event_bookLaundryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookFoodBtn;
    private javax.swing.JButton bookGameBtn;
    private javax.swing.JButton bookLaundryBtn;
    private javax.swing.JButton bookPoolBtn;
    private javax.swing.JButton bookVehicleBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton shopBtn;
    private javax.swing.JPanel userLeftPanel;
    private javax.swing.JPanel userRightPanel;
    // End of variables declaration//GEN-END:variables
}
