/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import Business.EcoSystem;
import Business.FoodandBev.Menu.FBItem;
import Business.User.User;
import Business.WorkRequest.FoodBevWorkRequest;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.MutableComboBoxModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rushang
 */
public class FoodBookingPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodBookingPanel
     */
    EcoSystem system;
    User user;
    ArrayList<FBItem> foodOrderList;

    public FoodBookingPanel(EcoSystem system, User user) {
        initComponents();

        foodOrderList = new ArrayList<FBItem>();
        this.system = system;
        this.user = user;

        MutableComboBoxModel<String> model = new DefaultComboBoxModel<String>();

        for (FBItem itemList : system.getFBItemDirectory().getFbItemDirectoryList()) {
            model.addElement(itemList.getFbName());
        }

        chooseFoodDropdown.setModel(model);

        itemNameTxt.setEditable(false);
        itemCategoryTxt.setEditable(false);
        itemPriceTxt.setEditable(false);

        populateRequestTable();
        formatRows();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chooseFoodDropdown = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        itemNameTxt = new javax.swing.JTextField();
        viewDetailsBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        itemCategoryTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        itemPriceTxt = new javax.swing.JTextField();
        addItemBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemListTable = new javax.swing.JTable();
        bookOrderBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderStatusTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        removeItemBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 102, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Book Food and Beverages");
        add(jLabel1);
        jLabel1.setBounds(620, 20, 380, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Choose a Food or Beverage:");
        add(jLabel2);
        jLabel2.setBounds(570, 150, 250, 25);

        add(chooseFoodDropdown);
        chooseFoodDropdown.setBounds(830, 150, 260, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Item Name:");
        add(jLabel3);
        jLabel3.setBounds(150, 230, 140, 25);

        itemNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add(itemNameTxt);
        itemNameTxt.setBounds(260, 230, 170, 31);

        viewDetailsBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });
        add(viewDetailsBtn);
        viewDetailsBtn.setBounds(1160, 140, 170, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Item Category:");
        add(jLabel4);
        jLabel4.setBounds(470, 230, 130, 25);

        itemCategoryTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itemCategoryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoryTxtActionPerformed(evt);
            }
        });
        add(itemCategoryTxt);
        itemCategoryTxt.setBounds(610, 230, 170, 31);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Item Price:");
        add(jLabel5);
        jLabel5.setBounds(810, 230, 110, 25);

        itemPriceTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(itemPriceTxt);
        itemPriceTxt.setBounds(920, 230, 170, 26);

        addItemBtn.setBackground(new java.awt.Color(0, 0, 0));
        addItemBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        addItemBtn.setText("Add Item");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });
        add(addItemBtn);
        addItemBtn.setBounds(1160, 220, 170, 50);

        itemListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Category", "Item Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(itemListTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 310, 1310, 240);

        bookOrderBtn.setBackground(new java.awt.Color(0, 0, 0));
        bookOrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookOrderBtn.setText("Book Order");
        bookOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookOrderBtnActionPerformed(evt);
            }
        });
        add(bookOrderBtn);
        bookOrderBtn.setBounds(1210, 570, 140, 50);

        orderStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "List of Items", "Total Price", "Order Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderStatusTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(100, 690, 1310, 240);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Food and Beverage Order Status");
        add(jLabel6);
        jLabel6.setBounds(570, 640, 400, 40);

        removeItemBtn.setBackground(new java.awt.Color(0, 0, 0));
        removeItemBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        removeItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeItemBtn.setText("Remove Item");
        removeItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemBtnActionPerformed(evt);
            }
        });
        add(removeItemBtn);
        removeItemBtn.setBounds(1030, 570, 160, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here:

        try {
            if (chooseFoodDropdown.getSelectedItem() != null) {

                String itemName = String.valueOf(chooseFoodDropdown.getSelectedItem());
                FBItem itemDetails = system.getFBItemDirectory().getItemByName(itemName);

                itemNameTxt.setText(itemDetails.getFbName());
                itemCategoryTxt.setText(itemDetails.getCategory());
                itemPriceTxt.setText(String.valueOf(itemDetails.getPrice()));

            } else {
                JOptionPane.showMessageDialog(this, "Choose a valid Food or Beverage item for viewing");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Choose a valid Food or Beverage item for viewing");
        }
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        // TODO add your handling code here:

        try {

            DefaultTableModel itemListModel = (DefaultTableModel) itemListTable.getModel();

            if (chooseFoodDropdown.getSelectedItem() != null) {

                String itemName = String.valueOf(chooseFoodDropdown.getSelectedItem());
                FBItem itemDetails = system.getFBItemDirectory().getItemByName(itemName);

                Object[] newRow = new Object[3];
                newRow[0] = itemDetails.getFbName();
                newRow[1] = itemDetails.getCategory();
                newRow[2] = itemDetails.getPrice();

                itemListModel.addRow(newRow);
                foodOrderList.add(itemDetails);
                
                clearFields();

            } else {
                JOptionPane.showMessageDialog(this, "Choose a valid Food or Beverage item for adding to list");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Choose a valid Food or Beverage item for adding to list");
        }
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void removeItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemBtnActionPerformed
        // TODO add your handling code here:

        try {
            int index = itemListTable.getSelectedRow();

            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Please select a Food or Beverage item to be removed from list");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) itemListTable.getModel();
            String itemName = String.valueOf(model.getValueAt(index, 0));
            FBItem itemDetails = system.getFBItemDirectory().getItemByName(itemName);

            model.removeRow(index);
            foodOrderList.remove(itemDetails);

            JOptionPane.showMessageDialog(this, "Food or Beverage item removed successfully from list");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select a Food or Beverage item to be removed from list");
        }
    }//GEN-LAST:event_removeItemBtnActionPerformed

    private void bookOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookOrderBtnActionPerformed
        // TODO add your handling code here:

        FoodBevWorkRequest bookFoodBev = new FoodBevWorkRequest();

        try {
            DefaultTableModel model = (DefaultTableModel) itemListTable.getModel();
            if (model.getRowCount() != 0) {

                bookFoodBev.setFbItemDetails(foodOrderList);
                bookFoodBev.setUserId(user.getUserId());
                bookFoodBev.setStatus("Pending");

                system.getFoodBevWorkRequestDirectory().getFoodBevWorkRequestList().add(bookFoodBev);

                JOptionPane.showMessageDialog(this, "Food and Beverage order request sent to Manager");

                foodOrderList = new ArrayList<FBItem>();
                populateRequestTable();

                model.setRowCount(0);
                clearFields();
                formatRows();
                
            } else {
                JOptionPane.showMessageDialog(this, "Choose valid Food and Beverage items for booking");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Choose valid Food and Beverage items for booking");
        }
    }//GEN-LAST:event_bookOrderBtnActionPerformed

    private void itemCategoryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCategoryTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton bookOrderBtn;
    private javax.swing.JComboBox<String> chooseFoodDropdown;
    private javax.swing.JTextField itemCategoryTxt;
    private javax.swing.JTable itemListTable;
    private javax.swing.JTextField itemNameTxt;
    private javax.swing.JTextField itemPriceTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderStatusTable;
    private javax.swing.JButton removeItemBtn;
    private javax.swing.JButton viewDetailsBtn;
    // End of variables declaration//GEN-END:variables

    private void populateRequestTable() {

        try {
            DefaultTableModel model = (DefaultTableModel) orderStatusTable.getModel();
            model.setRowCount(0);

            for (FoodBevWorkRequest fbWorkRequest : system.getFoodBevWorkRequestDirectory().getFoodBevWorkRequestList()) {

                String itemsList = "";
                float orderPrice = 0;
                if (fbWorkRequest.getUserId().equals(user.getUserId())) {

                    for (FBItem item : fbWorkRequest.getFbItemDetails()) {
                        itemsList += item.getFbName() + ", ";
                        orderPrice += item.getPrice();
                    }

                    Object[] newRow = new Object[3];
                    newRow[0] = itemsList;
                    newRow[1] = orderPrice;
                    newRow[2] = fbWorkRequest.getStatus();

                    model.addRow(newRow);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearFields() {
        
        itemNameTxt.setText("");
        itemPriceTxt.setText("");
        itemCategoryTxt.setText("");
        
    }
    
    private void formatRows() {

        DefaultTableModel model = (DefaultTableModel) orderStatusTable.getModel();

        orderStatusTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = String.valueOf(model.getValueAt(row, 2));
                c.setBackground(status.equals("Pending") ? Color.WHITE : status.equals("Approved") ? Color.GREEN : Color.RED);
                return c;
            }
        });

    }
}
