/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Business.EcoSystem;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Business.User.User;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import ui.Admin.AdminHomePanel;
import ui.Customer.CustomerHomePanel;
import ui.FoodMenu.FoodandBevPanel;
import ui.Purchase.ShopPanel;
import ui.Gaming.BookGamePanel;
import ui.JanitorSchedule.JanitorPanel;
import ui.Laundry.BookLaundryPanel;
import ui.Pool.BookPoolPanel;
import ui.Vehicle.BookVehiclePanel;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;

/**
 *
 * @author RAHUL
 */
public class LoginPanel extends javax.swing.JPanel {
    
     private Image backgroundImage;


    private EcoSystem system;
    private javax.swing.JSplitPane SplitPane;


    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(EcoSystem system, javax.swing.JSplitPane SplitPane) {
        initComponents();
        this.system = system;
        this.SplitPane = SplitPane;
        backgroundImage = new ImageIcon(getClass().getResource("/images/login-screen.jpg")).getImage();
        repaint();

    }

    public void resetData() {
        txtEUserName.setText("");
        txtEPassword.setText("");
    }
     @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (backgroundImage != null) {
            // Apply the blur effect on the background image
            BufferedImage blurredImage = blurImage(toBufferedImage(backgroundImage));
            g.drawImage(blurredImage, 0, 0, getWidth(), getHeight(), this);
        }
    }

    private BufferedImage blurImage(BufferedImage img) {
        try {
            float[] matrix = new float[9];
            for (int i = 0; i < matrix.length; i++) {
                matrix[i] = 1f / 9f; // Simple average blur matrix
            }
            Kernel kernel = new Kernel(3, 3, matrix);
            ConvolveOp convolveOp = new ConvolveOp(kernel, ConvolveOp.EDGE_NO_OP, null);
            return convolveOp.filter(img, null);
        } catch (Exception e) {
            e.printStackTrace();
            return img; // Return original image if an error occurs
        }
    }

    private BufferedImage toBufferedImage(Image img) {
        if (img instanceof BufferedImage) {
            return (BufferedImage) img;
        }
        // Create a buffered image
        BufferedImage bimage = new BufferedImage(
                img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);
        Graphics2D bGr = bimage.createGraphics();
        bGr.drawImage(img, 0, 0, null);
        bGr.dispose();
        return bimage;
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLoginUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEUserName = new javax.swing.JTextField();
        txtEPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 0, 204));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setLayout(null);

        btnLoginUser.setBackground(new java.awt.Color(0, 0, 0));
        btnLoginUser.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginUser.setText("LOGIN");
        btnLoginUser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginUser);
        btnLoginUser.setBounds(190, 230, 127, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 70, 240, 40);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 240, 40);
        jPanel1.add(txtEUserName);
        txtEUserName.setBounds(220, 70, 240, 40);
        jPanel1.add(txtEPassword);
        txtEPassword.setBounds(220, 130, 240, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginUserActionPerformed
    
        String userName = txtEUserName.getText();
        String password = txtEPassword.getText();
        ArrayList<User> list = system.getUserDirectory().getUsers();

        if (userName.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all the details !!");
        } else {
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "You have not registered !!");
            } else {
                int index = 0;
                for (User temp : list) {
                    if (userName.equalsIgnoreCase(temp.getUserName()) && password.equalsIgnoreCase(temp.getPassword())) {
                        if (temp.getRoleType().equalsIgnoreCase("Customer")) {
                            CustomerHomePanel customerHomePanel = new CustomerHomePanel(system, temp);
                            SplitPane.setRightComponent(customerHomePanel);
                        } else if (temp.getRoleType().equalsIgnoreCase("Admin")) {
                            AdminHomePanel adminHomePanel = new AdminHomePanel(system);
                            SplitPane.setRightComponent(adminHomePanel);
                        } else if (temp.getRoleType().equalsIgnoreCase("Vehicle Contractor")) {
                            BookVehiclePanel bookVehiclePanel = new BookVehiclePanel(system);
                            SplitPane.setRightComponent(bookVehiclePanel);
                        } else if (temp.getRoleType().equalsIgnoreCase("Pool Incharge")) {
                            BookPoolPanel bookPoolPanel = new BookPoolPanel(system);
                            SplitPane.setRightComponent(bookPoolPanel);
                        } else if (temp.getRoleType().equalsIgnoreCase("Food Manager")) {
                            FoodandBevPanel foodandBevPanel = new FoodandBevPanel(system);
                            SplitPane.setRightComponent(foodandBevPanel);
                        } else if (temp.getRoleType().equalsIgnoreCase("Gaming Incharge")) {
                            BookGamePanel bookGamePanel = new BookGamePanel(system);
                            SplitPane.setRightComponent(bookGamePanel);
                        } else if (temp.getRoleType().equalsIgnoreCase("Laundry Manager")) {
                            BookLaundryPanel bookLaundryPanel = new BookLaundryPanel(system);
                            SplitPane.setRightComponent(bookLaundryPanel);
                        } else if (temp.getRoleType().equalsIgnoreCase("Janitor")) {
                            JanitorPanel janitorPanel = new JanitorPanel(system, temp);
                            SplitPane.setRightComponent(janitorPanel);
                        } else if (temp.getRoleType().equalsIgnoreCase("Shop Manager")) {
                            ShopPanel shopPanel = new ShopPanel(system);
                            SplitPane.setRightComponent(shopPanel);
                        }
                    } else {
                        index++;
                    }
                }
                if (index == list.size()) {
                    JOptionPane.showMessageDialog(this, "You have not registered !!");
                    resetData();
                }
            }
        }

//                JOptionPane.showMessageDialog(this, "Invalid User");
    }//GEN-LAST:event_btnLoginUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEPassword;
    private javax.swing.JTextField txtEUserName;
    // End of variables declaration//GEN-END:variables
}
