/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.LaundryBooking;

import Business.EcoSystem;
import javax.swing.JOptionPane;
import ui.LaundryBooking.ManageLaundryPanel;
import ui.PoolBooking.HomePoolPanel;

/**
 *
 * @author Sushant
 */
public class BookLaundryPanel extends javax.swing.JPanel {
    private EcoSystem system;

    /**
     * Creates new form BookLaundryPanel
     */
    public BookLaundryPanel(EcoSystem system) {
        initComponents();
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnManageLaundry = new javax.swing.JButton();
        btnRequestQueue = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnRequestQueue1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));

        btnManageLaundry.setBackground(new java.awt.Color(0, 0, 0));
        btnManageLaundry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageLaundry.setForeground(new java.awt.Color(255, 255, 255));
        btnManageLaundry.setText("MANAGE CATEGORY");
        btnManageLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLaundryActionPerformed(evt);
            }
        });

        btnRequestQueue.setBackground(new java.awt.Color(0, 0, 0));
        btnRequestQueue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRequestQueue.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestQueue.setText("MANAGE REQUESTS");
        btnRequestQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestQueueActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnRequestQueue1.setBackground(new java.awt.Color(0, 0, 0));
        btnRequestQueue1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRequestQueue1.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestQueue1.setText("MANAGE REQUESTS");
        btnRequestQueue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestQueue1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageLaundry)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRequestQueue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnRequestQueue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnManageLaundry)
                .addGap(29, 29, 29)
                .addComponent(btnRequestQueue)
                .addGap(35, 35, 35)
                .addComponent(btnHome)
                .addGap(39, 39, 39)
                .addComponent(btnRequestQueue1)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 102, 255));
        jPanel2.setLayout(null);
        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1181, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLaundryActionPerformed
        // TODO add your handling code here:
         try {
            ManageLaundryPanel managelaundryPanel = new ManageLaundryPanel(system);
            jSplitPane1.setRightComponent(managelaundryPanel);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnManageLaundryActionPerformed

    private void btnRequestQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestQueueActionPerformed
        // TODO add your handling code here:
         try {
            ManageLaundryRequestsPanel manageRequestsPanel  = new ManageLaundryRequestsPanel(system);
            jSplitPane1.setRightComponent(manageRequestsPanel);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRequestQueueActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        try {
            HomeLaundryPanel homeLaundryPanel = new HomeLaundryPanel();
            jSplitPane1.setRightComponent(homeLaundryPanel);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnRequestQueue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestQueue1ActionPerformed
        // TODO add your handling code here:
        try {
            ManagePoolRequestsPanel manageRequestsPanel  = new ManagePoolRequestsPanel(system);
            jSplitPane1.setRightComponent(manageRequestsPanel);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRequestQueue1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnManageLaundry;
    private javax.swing.JButton btnRequestQueue;
    private javax.swing.JButton btnRequestQueue1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
