/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import Business.EcoSystem;
import Business.TransactionHistory.CustomerTransaction;
import Business.User.User;
import Business.WorkRequest.FoodBevWorkRequest;
import Business.WorkRequest.GameWorkRequest;
import Business.WorkRequest.LaundryWorkRequest;
import Business.WorkRequest.PoolWorkRequest;
import Business.WorkRequest.VehicleWorkRequest;

/**
 *
 * @author Rushang
 */
public class AdminAnalyticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminAnalyticsPanel
     */
    EcoSystem system;

    public AdminAnalyticsPanel(EcoSystem system) {
        initComponents();
        this.system = system;
        
        customerTxt.setEditable(false);
        foodManagerTxt.setEditable(false);
        foodManagerTxt2.setEditable(false);
        gameInchargeTxt.setEditable(false);
        gameInchargeTxt2.setEditable(false);
        janitorTxt.setEditable(false);
        laundryManagerTxt.setEditable(false);
        laundryManagerTxt2.setEditable(false);
        poolInchargeTxt.setEditable(false);
        poolInchargeTxt2.setEditable(false);
        shopManagerTxt.setEditable(false);
        totalRequestTxt.setEditable(false);
        totalRevenueTxt1.setEditable(false);
        vehicleContractorTxt.setEditable(false);
        vehicleContractorTxt2.setEditable(false);

        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        totalRequestTxt = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        customerTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vehicleContractorTxt = new javax.swing.JTextField();
        foodManagerTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gameInchargeTxt = new javax.swing.JTextField();
        janitorTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        laundryManagerTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        poolInchargeTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        shopManagerTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        gameInchargeTxt2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        totalRevenueTxt1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vehicleContractorTxt2 = new javax.swing.JTextField();
        foodManagerTxt2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        laundryManagerTxt2 = new javax.swing.JTextField();
        poolInchargeTxt2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 102, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Admin Analytics");

        jLabel15.setText("Total requests:");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel8.setText("Vehicle Contractors:");

        jLabel9.setText("Food Managers:");

        jLabel10.setText("Gaming Incharges:");

        jLabel11.setText("Janitors:");

        jLabel12.setText("Laundry Managers:");

        jLabel13.setText("Pool Incharges:");

        jLabel14.setText("Shop Managers:");

        shopManagerTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopManagerTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Total number of Users");

        jLabel7.setText("Customers:");

        jDesktopPane1.setLayer(customerTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(vehicleContractorTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(foodManagerTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(gameInchargeTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(janitorTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(laundryManagerTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(poolInchargeTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(shopManagerTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(391, 391, 391))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(vehicleContractorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(foodManagerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gameInchargeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(customerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(160, 160, 160)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(poolInchargeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(janitorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shopManagerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(laundryManagerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(51, Short.MAX_VALUE))))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {customerTxt, foodManagerTxt, gameInchargeTxt, jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel7, jLabel8, jLabel9, janitorTxt, laundryManagerTxt, poolInchargeTxt, shopManagerTxt, vehicleContractorTxt});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(customerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(janitorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vehicleContractorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(poolInchargeTxt))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(foodManagerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shopManagerTxt))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(gameInchargeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laundryManagerTxt))
                .addContainerGap())
        );

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Pending requests");

        jLabel21.setText("Gaming:");

        jLabel22.setText("Laundry Managers:");

        jLabel23.setText("Pool Incharges:");

        jLabel24.setText("Vehicle:");

        jLabel5.setText("Total Resort Revenue:");

        foodManagerTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodManagerTxt2ActionPerformed(evt);
            }
        });

        jLabel25.setText("Food and Beverages:");

        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(gameInchargeTxt2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(totalRevenueTxt1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(vehicleContractorTxt2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(foodManagerTxt2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(laundryManagerTxt2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(poolInchargeTxt2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel21))
                        .addGap(25, 25, 25)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gameInchargeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                        .addComponent(foodManagerTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane2Layout.createSequentialGroup()
                                        .addComponent(vehicleContractorTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(235, 235, 235)
                                        .addComponent(jLabel22)))
                                .addGap(39, 39, 39)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(laundryManagerTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(poolInchargeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jLabel3))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel5)
                        .addGap(55, 55, 55)
                        .addComponent(totalRevenueTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(vehicleContractorTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(foodManagerTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(poolInchargeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gameInchargeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(totalRevenueTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laundryManagerTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1770, 1770, 1770)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(totalRequestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(627, 627, 627)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDesktopPane1)
                            .addComponent(jDesktopPane2))))
                .addContainerGap(1544, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(totalRequestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void shopManagerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopManagerTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shopManagerTxtActionPerformed

    private void foodManagerTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodManagerTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodManagerTxt2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerTxt;
    private javax.swing.JTextField foodManagerTxt;
    private javax.swing.JTextField foodManagerTxt2;
    private javax.swing.JTextField gameInchargeTxt;
    private javax.swing.JTextField gameInchargeTxt2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField janitorTxt;
    private javax.swing.JTextField laundryManagerTxt;
    private javax.swing.JTextField laundryManagerTxt2;
    private javax.swing.JTextField poolInchargeTxt;
    private javax.swing.JTextField poolInchargeTxt2;
    private javax.swing.JTextField shopManagerTxt;
    private javax.swing.JTextField totalRequestTxt;
    private javax.swing.JTextField totalRevenueTxt1;
    private javax.swing.JTextField vehicleContractorTxt;
    private javax.swing.JTextField vehicleContractorTxt2;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {

        try {

            int customerCount = 0;
            int vehicleContractorCount = 0;
            int foodManagerCount = 0;
            int poolInchargeCount = 0;
            int gameInchargeCount = 0;
            int shopManagerCount = 0;
            int laundryManagerCount = 0;
            int janitorCount = 0;
            int totalRequestCount = 0;
            int vehiclePendingRequestCount = 0;
            int foodBevPendingRequestCount = 0;
            int poolPendingRequestCount = 0;
            int gamePendingRequestCount = 0;
            int laundryPendingRequestCount = 0;
            float totalRevenue = 0;

            for (User user : system.getUserDirectory().getUsers()) {

                if (user.getRoleType().equals("Customer")) {
                    customerCount += 1;
                } else if (user.getRoleType().equals("Vehicle Contractor")) {
                    vehicleContractorCount += 1;
                } else if (user.getRoleType().equals("Pool Incharge")) {
                    poolInchargeCount += 1;
                } else if (user.getRoleType().equals("Gaming Incharge")) {
                    gameInchargeCount += 1;
                } else if (user.getRoleType().equals("Laundry Manager")) {
                    laundryManagerCount += 1;
                } else if (user.getRoleType().equals("Janitor")) {
                    janitorCount += 1;
                } else if (user.getRoleType().equals("Food Manager")) {
                    foodManagerCount += 1;
                } else if (user.getRoleType().equals("Shop Manager")) {
                    shopManagerCount += 1;
                }
            }

            for (CustomerTransaction transaction : system.getCustomerTransactionDirectory().getCustomerTransactionList()) {

                totalRevenue += transaction.getPrice();
            }

            totalRequestCount = system.getFoodBevWorkRequestDirectory().getFoodBevWorkRequestList().size()
                    + system.getGameWorkRequestDirectory().getGameWorkRequestList().size()
                    + system.getLaundryWorkRequestDirectory().getLaundryWorkRequestList().size()
                    + system.getPoolWorkRequestDirectory().getPoolWorkRequestList().size()
                    + system.getVehicleWorkRequestDirectory().getVehicleWorkRequestList().size();

            for (VehicleWorkRequest vehicleWorkRequest : system.getVehicleWorkRequestDirectory().getVehicleWorkRequestList()) {

                if (vehicleWorkRequest.getStatus().equals("Pending")) {
                    vehiclePendingRequestCount += 1;
                }
            }

            for (FoodBevWorkRequest foodBevWorkRequest : system.getFoodBevWorkRequestDirectory().getFoodBevWorkRequestList()) {

                if (foodBevWorkRequest.getStatus().equals("Pending")) {
                    foodBevPendingRequestCount += 1;
                }
            }

            for (PoolWorkRequest poolWorkRequest : system.getPoolWorkRequestDirectory().getPoolWorkRequestList()) {

                if (poolWorkRequest.getStatus().equals("Pending")) {
                    poolPendingRequestCount += 1;
                }
            }

            for (GameWorkRequest gameWorkRequest : system.getGameWorkRequestDirectory().getGameWorkRequestList()) {

                if (gameWorkRequest.getStatus().equals("Pending")) {
                    gamePendingRequestCount += 1;
                }
            }

            for (LaundryWorkRequest laundryWorkRequest : system.getLaundryWorkRequestDirectory().getLaundryWorkRequestList()) {

                if (laundryWorkRequest.getStatus().equals("Pending")) {
                    laundryPendingRequestCount += 1;
                }
            }

            customerTxt.setText(String.valueOf(customerCount));
            vehicleContractorTxt.setText(String.valueOf(vehicleContractorCount));
            poolInchargeTxt.setText(String.valueOf(poolInchargeCount));
            gameInchargeTxt.setText(String.valueOf(gameInchargeCount));
            laundryManagerTxt.setText(String.valueOf(laundryManagerCount));
            janitorTxt.setText(String.valueOf(janitorCount));
            foodManagerTxt.setText(String.valueOf(foodManagerCount));
            shopManagerTxt.setText(String.valueOf(shopManagerCount));
            totalRevenueTxt1.setText(String.valueOf(totalRevenue));
            totalRequestTxt.setText(String.valueOf(totalRequestCount));
            vehicleContractorTxt2.setText(String.valueOf(vehiclePendingRequestCount));
            poolInchargeTxt2.setText(String.valueOf(poolPendingRequestCount));
            gameInchargeTxt2.setText(String.valueOf(gamePendingRequestCount));
            laundryManagerTxt2.setText(String.valueOf(laundryPendingRequestCount));
            foodManagerTxt2.setText(String.valueOf(foodBevPendingRequestCount));

        } catch (Exception e) {

        }
    }
}
